// Code generated by entc, DO NOT EDIT.

package lessonplan

const (
	// Label holds the string label denoting the lessonplan type in the database.
	Label = "lessonplan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoom holds the string denoting the room field in the database.
	FieldRoom = "room"

	// EdgeGroupID holds the string denoting the group_id edge name in mutations.
	EdgeGroupID = "Group_id"
	// EdgeCourseID holds the string denoting the course_id edge name in mutations.
	EdgeCourseID = "Course_ID"
	// EdgeProfessorID holds the string denoting the professor_id edge name in mutations.
	EdgeProfessorID = "Professor_ID"

	// Table holds the table name of the lessonplan in the database.
	Table = "lessonplans"
	// GroupIDTable is the table the holds the Group_id relation/edge.
	GroupIDTable = "lessonplans"
	// GroupIDInverseTable is the table name for the Section entity.
	// It exists in this package in order to avoid circular dependency with the "section" package.
	GroupIDInverseTable = "sections"
	// GroupIDColumn is the table column denoting the Group_id relation/edge.
	GroupIDColumn = "section_sec_id"
	// CourseIDTable is the table the holds the Course_ID relation/edge.
	CourseIDTable = "lessonplans"
	// CourseIDInverseTable is the table name for the Subject entity.
	// It exists in this package in order to avoid circular dependency with the "subject" package.
	CourseIDInverseTable = "subjects"
	// CourseIDColumn is the table column denoting the Course_ID relation/edge.
	CourseIDColumn = "subject_subject_id"
	// ProfessorIDTable is the table the holds the Professor_ID relation/edge.
	ProfessorIDTable = "lessonplans"
	// ProfessorIDInverseTable is the table name for the Teacher entity.
	// It exists in this package in order to avoid circular dependency with the "teacher" package.
	ProfessorIDInverseTable = "teachers"
	// ProfessorIDColumn is the table column denoting the Professor_ID relation/edge.
	ProfessorIDColumn = "teacher_teachers_id"
)

// Columns holds all SQL columns for lessonplan fields.
var Columns = []string{
	FieldID,
	FieldRoom,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Lessonplan type.
var ForeignKeys = []string{
	"section_sec_id",
	"subject_subject_id",
	"teacher_teachers_id",
}

var (
	// RoomValidator is a validator for the "Room" field. It is called by the builders before save.
	RoomValidator func(string) error
)
