// Code generated by entc, DO NOT EDIT.

package lessonplan

import (
	"github.com/USER/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Room applies equality check predicate on the "Room" field. It's identical to RoomEQ.
func Room(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoom), v))
	})
}

// RoomEQ applies the EQ predicate on the "Room" field.
func RoomEQ(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoom), v))
	})
}

// RoomNEQ applies the NEQ predicate on the "Room" field.
func RoomNEQ(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRoom), v))
	})
}

// RoomIn applies the In predicate on the "Room" field.
func RoomIn(vs ...string) predicate.Lessonplan {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Lessonplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRoom), v...))
	})
}

// RoomNotIn applies the NotIn predicate on the "Room" field.
func RoomNotIn(vs ...string) predicate.Lessonplan {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Lessonplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRoom), v...))
	})
}

// RoomGT applies the GT predicate on the "Room" field.
func RoomGT(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRoom), v))
	})
}

// RoomGTE applies the GTE predicate on the "Room" field.
func RoomGTE(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRoom), v))
	})
}

// RoomLT applies the LT predicate on the "Room" field.
func RoomLT(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRoom), v))
	})
}

// RoomLTE applies the LTE predicate on the "Room" field.
func RoomLTE(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRoom), v))
	})
}

// RoomContains applies the Contains predicate on the "Room" field.
func RoomContains(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRoom), v))
	})
}

// RoomHasPrefix applies the HasPrefix predicate on the "Room" field.
func RoomHasPrefix(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRoom), v))
	})
}

// RoomHasSuffix applies the HasSuffix predicate on the "Room" field.
func RoomHasSuffix(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRoom), v))
	})
}

// RoomEqualFold applies the EqualFold predicate on the "Room" field.
func RoomEqualFold(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRoom), v))
	})
}

// RoomContainsFold applies the ContainsFold predicate on the "Room" field.
func RoomContainsFold(v string) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRoom), v))
	})
}

// HasGroupID applies the HasEdge predicate on the "Group_id" edge.
func HasGroupID() predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(GroupIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupIDTable, GroupIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupIDWith applies the HasEdge predicate on the "Group_id" edge with a given conditions (other predicates).
func HasGroupIDWith(preds ...predicate.Section) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(GroupIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupIDTable, GroupIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCourseID applies the HasEdge predicate on the "Course_ID" edge.
func HasCourseID() predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CourseIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CourseIDTable, CourseIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCourseIDWith applies the HasEdge predicate on the "Course_ID" edge with a given conditions (other predicates).
func HasCourseIDWith(preds ...predicate.Subject) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CourseIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CourseIDTable, CourseIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProfessorID applies the HasEdge predicate on the "Professor_ID" edge.
func HasProfessorID() predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProfessorIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProfessorIDTable, ProfessorIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProfessorIDWith applies the HasEdge predicate on the "Professor_ID" edge with a given conditions (other predicates).
func HasProfessorIDWith(preds ...predicate.Teacher) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProfessorIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProfessorIDTable, ProfessorIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Lessonplan) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Lessonplan) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Lessonplan) predicate.Lessonplan {
	return predicate.Lessonplan(func(s *sql.Selector) {
		p(s.Not())
	})
}
