// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgeUserID holds the string denoting the user_id edge name in mutations.
	EdgeUserID = "User_ID"

	// Table holds the table name of the user in the database.
	Table = "users"
	// UserIDTable is the table the holds the User_ID relation/edge.
	UserIDTable = "teachers"
	// UserIDInverseTable is the table name for the Teacher entity.
	// It exists in this package in order to avoid circular dependency with the "teacher" package.
	UserIDInverseTable = "teachers"
	// UserIDColumn is the table column denoting the User_ID relation/edge.
	UserIDColumn = "user_user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUserEmail,
	FieldPassword,
}
