// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Lessonplan is the predicate function for lessonplan builders.
type Lessonplan func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
