// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/USER/app/ent/lessonplan"
	"github.com/USER/app/ent/schema"
	"github.com/USER/app/ent/section"
	"github.com/USER/app/ent/subject"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	lessonplanFields := schema.Lessonplan{}.Fields()
	_ = lessonplanFields
	// lessonplanDescRoom is the schema descriptor for Room field.
	lessonplanDescRoom := lessonplanFields[0].Descriptor()
	// lessonplan.RoomValidator is a validator for the "Room" field. It is called by the builders before save.
	lessonplan.RoomValidator = lessonplanDescRoom.Validators[0].(func(string) error)
	sectionFields := schema.Section{}.Fields()
	_ = sectionFields
	// sectionDescGroup is the schema descriptor for Group field.
	sectionDescGroup := sectionFields[0].Descriptor()
	// section.GroupValidator is a validator for the "Group" field. It is called by the builders before save.
	section.GroupValidator = sectionDescGroup.Validators[0].(func(int) error)
	// sectionDescRecieve is the schema descriptor for recieve field.
	sectionDescRecieve := sectionFields[1].Descriptor()
	// section.RecieveValidator is a validator for the "recieve" field. It is called by the builders before save.
	section.RecieveValidator = sectionDescRecieve.Validators[0].(func(int) error)
	// sectionDescSeatLeft is the schema descriptor for Seat_left field.
	sectionDescSeatLeft := sectionFields[2].Descriptor()
	// section.SeatLeftValidator is a validator for the "Seat_left" field. It is called by the builders before save.
	section.SeatLeftValidator = sectionDescSeatLeft.Validators[0].(func(int) error)
	// sectionDescRoom is the schema descriptor for Room field.
	sectionDescRoom := sectionFields[3].Descriptor()
	// section.RoomValidator is a validator for the "Room" field. It is called by the builders before save.
	section.RoomValidator = sectionDescRoom.Validators[0].(func(string) error)
	// sectionDescDateTime is the schema descriptor for Date_Time field.
	sectionDescDateTime := sectionFields[4].Descriptor()
	// section.DateTimeValidator is a validator for the "Date_Time" field. It is called by the builders before save.
	section.DateTimeValidator = sectionDescDateTime.Validators[0].(func(string) error)
	subjectFields := schema.Subject{}.Fields()
	_ = subjectFields
	// subjectDescCredit is the schema descriptor for Credit field.
	subjectDescCredit := subjectFields[1].Descriptor()
	// subject.CreditValidator is a validator for the "Credit" field. It is called by the builders before save.
	subject.CreditValidator = subjectDescCredit.Validators[0].(func(int) error)
	// subjectDescPrice is the schema descriptor for Price field.
	subjectDescPrice := subjectFields[2].Descriptor()
	// subject.PriceValidator is a validator for the "Price" field. It is called by the builders before save.
	subject.PriceValidator = subjectDescPrice.Validators[0].(func(float64) error)
}
