// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/USER/app/ent/lessonplan"
	"github.com/USER/app/ent/subject"
	"github.com/USER/app/ent/teacher"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SubjectCreate is the builder for creating a Subject entity.
type SubjectCreate struct {
	config
	mutation *SubjectMutation
	hooks    []Hook
}

// SetSubjectName sets the Subject_Name field.
func (sc *SubjectCreate) SetSubjectName(s string) *SubjectCreate {
	sc.mutation.SetSubjectName(s)
	return sc
}

// SetCredit sets the Credit field.
func (sc *SubjectCreate) SetCredit(i int) *SubjectCreate {
	sc.mutation.SetCredit(i)
	return sc
}

// SetPrice sets the Price field.
func (sc *SubjectCreate) SetPrice(f float64) *SubjectCreate {
	sc.mutation.SetPrice(f)
	return sc
}

// SetProfessorIDID sets the Professor_ID edge to Teacher by id.
func (sc *SubjectCreate) SetProfessorIDID(id int) *SubjectCreate {
	sc.mutation.SetProfessorIDID(id)
	return sc
}

// SetNillableProfessorIDID sets the Professor_ID edge to Teacher by id if the given value is not nil.
func (sc *SubjectCreate) SetNillableProfessorIDID(id *int) *SubjectCreate {
	if id != nil {
		sc = sc.SetProfessorIDID(*id)
	}
	return sc
}

// SetProfessorID sets the Professor_ID edge to Teacher.
func (sc *SubjectCreate) SetProfessorID(t *Teacher) *SubjectCreate {
	return sc.SetProfessorIDID(t.ID)
}

// AddSubjectIDIDs adds the Subject_ID edge to Lessonplan by ids.
func (sc *SubjectCreate) AddSubjectIDIDs(ids ...int) *SubjectCreate {
	sc.mutation.AddSubjectIDIDs(ids...)
	return sc
}

// AddSubjectID adds the Subject_ID edges to Lessonplan.
func (sc *SubjectCreate) AddSubjectID(l ...*Lessonplan) *SubjectCreate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return sc.AddSubjectIDIDs(ids...)
}

// Mutation returns the SubjectMutation object of the builder.
func (sc *SubjectCreate) Mutation() *SubjectMutation {
	return sc.mutation
}

// Save creates the Subject in the database.
func (sc *SubjectCreate) Save(ctx context.Context) (*Subject, error) {
	if _, ok := sc.mutation.SubjectName(); !ok {
		return nil, &ValidationError{Name: "Subject_Name", err: errors.New("ent: missing required field \"Subject_Name\"")}
	}
	if _, ok := sc.mutation.Credit(); !ok {
		return nil, &ValidationError{Name: "Credit", err: errors.New("ent: missing required field \"Credit\"")}
	}
	if v, ok := sc.mutation.Credit(); ok {
		if err := subject.CreditValidator(v); err != nil {
			return nil, &ValidationError{Name: "Credit", err: fmt.Errorf("ent: validator failed for field \"Credit\": %w", err)}
		}
	}
	if _, ok := sc.mutation.Price(); !ok {
		return nil, &ValidationError{Name: "Price", err: errors.New("ent: missing required field \"Price\"")}
	}
	if v, ok := sc.mutation.Price(); ok {
		if err := subject.PriceValidator(v); err != nil {
			return nil, &ValidationError{Name: "Price", err: fmt.Errorf("ent: validator failed for field \"Price\": %w", err)}
		}
	}
	var (
		err  error
		node *Subject
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubjectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubjectCreate) SaveX(ctx context.Context) *Subject {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *SubjectCreate) sqlSave(ctx context.Context) (*Subject, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *SubjectCreate) createSpec() (*Subject, *sqlgraph.CreateSpec) {
	var (
		s     = &Subject{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: subject.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: subject.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.SubjectName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: subject.FieldSubjectName,
		})
		s.SubjectName = value
	}
	if value, ok := sc.mutation.Credit(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: subject.FieldCredit,
		})
		s.Credit = value
	}
	if value, ok := sc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: subject.FieldPrice,
		})
		s.Price = value
	}
	if nodes := sc.mutation.ProfessorIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subject.ProfessorIDTable,
			Columns: []string{subject.ProfessorIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: teacher.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.SubjectIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subject.SubjectIDTable,
			Columns: []string{subject.SubjectIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lessonplan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
