// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/USER/app/ent/subject"
	"github.com/USER/app/ent/teacher"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Subject is the model entity for the Subject schema.
type Subject struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SubjectName holds the value of the "Subject_Name" field.
	SubjectName string `json:"Subject_Name,omitempty"`
	// Credit holds the value of the "Credit" field.
	Credit int `json:"Credit,omitempty"`
	// Price holds the value of the "Price" field.
	Price float64 `json:"Price,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubjectQuery when eager-loading is set.
	Edges              SubjectEdges `json:"edges"`
	teacher_teacher_id *int
}

// SubjectEdges holds the relations/edges for other nodes in the graph.
type SubjectEdges struct {
	// ProfessorID holds the value of the Professor_ID edge.
	ProfessorID *Teacher
	// SubjectID holds the value of the Subject_ID edge.
	SubjectID []*Lessonplan
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProfessorIDOrErr returns the ProfessorID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubjectEdges) ProfessorIDOrErr() (*Teacher, error) {
	if e.loadedTypes[0] {
		if e.ProfessorID == nil {
			// The edge Professor_ID was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: teacher.Label}
		}
		return e.ProfessorID, nil
	}
	return nil, &NotLoadedError{edge: "Professor_ID"}
}

// SubjectIDOrErr returns the SubjectID value or an error if the edge
// was not loaded in eager-loading.
func (e SubjectEdges) SubjectIDOrErr() ([]*Lessonplan, error) {
	if e.loadedTypes[1] {
		return e.SubjectID, nil
	}
	return nil, &NotLoadedError{edge: "Subject_ID"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subject) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},   // id
		&sql.NullString{},  // Subject_Name
		&sql.NullInt64{},   // Credit
		&sql.NullFloat64{}, // Price
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Subject) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // teacher_teacher_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subject fields.
func (s *Subject) assignValues(values ...interface{}) error {
	if m, n := len(values), len(subject.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Subject_Name", values[0])
	} else if value.Valid {
		s.SubjectName = value.String
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Credit", values[1])
	} else if value.Valid {
		s.Credit = int(value.Int64)
	}
	if value, ok := values[2].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field Price", values[2])
	} else if value.Valid {
		s.Price = value.Float64
	}
	values = values[3:]
	if len(values) == len(subject.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field teacher_teacher_id", value)
		} else if value.Valid {
			s.teacher_teacher_id = new(int)
			*s.teacher_teacher_id = int(value.Int64)
		}
	}
	return nil
}

// QueryProfessorID queries the Professor_ID edge of the Subject.
func (s *Subject) QueryProfessorID() *TeacherQuery {
	return (&SubjectClient{config: s.config}).QueryProfessorID(s)
}

// QuerySubjectID queries the Subject_ID edge of the Subject.
func (s *Subject) QuerySubjectID() *LessonplanQuery {
	return (&SubjectClient{config: s.config}).QuerySubjectID(s)
}

// Update returns a builder for updating this Subject.
// Note that, you need to call Subject.Unwrap() before calling this method, if this Subject
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Subject) Update() *SubjectUpdateOne {
	return (&SubjectClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Subject) Unwrap() *Subject {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subject is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Subject) String() string {
	var builder strings.Builder
	builder.WriteString("Subject(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", Subject_Name=")
	builder.WriteString(s.SubjectName)
	builder.WriteString(", Credit=")
	builder.WriteString(fmt.Sprintf("%v", s.Credit))
	builder.WriteString(", Price=")
	builder.WriteString(fmt.Sprintf("%v", s.Price))
	builder.WriteByte(')')
	return builder.String()
}

// Subjects is a parsable slice of Subject.
type Subjects []*Subject

func (s Subjects) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
