// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/USER/app/ent/lessonplan"
	"github.com/USER/app/ent/predicate"
	"github.com/USER/app/ent/subject"
	"github.com/USER/app/ent/teacher"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// TeacherUpdate is the builder for updating Teacher entities.
type TeacherUpdate struct {
	config
	hooks      []Hook
	mutation   *TeacherMutation
	predicates []predicate.Teacher
}

// Where adds a new predicate for the builder.
func (tu *TeacherUpdate) Where(ps ...predicate.Teacher) *TeacherUpdate {
	tu.predicates = append(tu.predicates, ps...)
	return tu
}

// SetTeacherName sets the Teacher_Name field.
func (tu *TeacherUpdate) SetTeacherName(s string) *TeacherUpdate {
	tu.mutation.SetTeacherName(s)
	return tu
}

// AddTeacherIDIDs adds the Teacher_ID edge to Subject by ids.
func (tu *TeacherUpdate) AddTeacherIDIDs(ids ...int) *TeacherUpdate {
	tu.mutation.AddTeacherIDIDs(ids...)
	return tu
}

// AddTeacherID adds the Teacher_ID edges to Subject.
func (tu *TeacherUpdate) AddTeacherID(s ...*Subject) *TeacherUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.AddTeacherIDIDs(ids...)
}

// AddTeachersIDIDs adds the Teachers_ID edge to Lessonplan by ids.
func (tu *TeacherUpdate) AddTeachersIDIDs(ids ...int) *TeacherUpdate {
	tu.mutation.AddTeachersIDIDs(ids...)
	return tu
}

// AddTeachersID adds the Teachers_ID edges to Lessonplan.
func (tu *TeacherUpdate) AddTeachersID(l ...*Lessonplan) *TeacherUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tu.AddTeachersIDIDs(ids...)
}

// Mutation returns the TeacherMutation object of the builder.
func (tu *TeacherUpdate) Mutation() *TeacherMutation {
	return tu.mutation
}

// RemoveTeacherIDIDs removes the Teacher_ID edge to Subject by ids.
func (tu *TeacherUpdate) RemoveTeacherIDIDs(ids ...int) *TeacherUpdate {
	tu.mutation.RemoveTeacherIDIDs(ids...)
	return tu
}

// RemoveTeacherID removes Teacher_ID edges to Subject.
func (tu *TeacherUpdate) RemoveTeacherID(s ...*Subject) *TeacherUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.RemoveTeacherIDIDs(ids...)
}

// RemoveTeachersIDIDs removes the Teachers_ID edge to Lessonplan by ids.
func (tu *TeacherUpdate) RemoveTeachersIDIDs(ids ...int) *TeacherUpdate {
	tu.mutation.RemoveTeachersIDIDs(ids...)
	return tu
}

// RemoveTeachersID removes Teachers_ID edges to Lessonplan.
func (tu *TeacherUpdate) RemoveTeachersID(l ...*Lessonplan) *TeacherUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tu.RemoveTeachersIDIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (tu *TeacherUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TeacherMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TeacherUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TeacherUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TeacherUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TeacherUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   teacher.Table,
			Columns: teacher.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: teacher.FieldID,
			},
		},
	}
	if ps := tu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.TeacherName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: teacher.FieldTeacherName,
		})
	}
	if nodes := tu.mutation.RemovedTeacherIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeacherIDTable,
			Columns: []string{teacher.TeacherIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subject.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.TeacherIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeacherIDTable,
			Columns: []string{teacher.TeacherIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subject.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := tu.mutation.RemovedTeachersIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeachersIDTable,
			Columns: []string{teacher.TeachersIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lessonplan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.TeachersIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeachersIDTable,
			Columns: []string{teacher.TeachersIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lessonplan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teacher.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// TeacherUpdateOne is the builder for updating a single Teacher entity.
type TeacherUpdateOne struct {
	config
	hooks    []Hook
	mutation *TeacherMutation
}

// SetTeacherName sets the Teacher_Name field.
func (tuo *TeacherUpdateOne) SetTeacherName(s string) *TeacherUpdateOne {
	tuo.mutation.SetTeacherName(s)
	return tuo
}

// AddTeacherIDIDs adds the Teacher_ID edge to Subject by ids.
func (tuo *TeacherUpdateOne) AddTeacherIDIDs(ids ...int) *TeacherUpdateOne {
	tuo.mutation.AddTeacherIDIDs(ids...)
	return tuo
}

// AddTeacherID adds the Teacher_ID edges to Subject.
func (tuo *TeacherUpdateOne) AddTeacherID(s ...*Subject) *TeacherUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.AddTeacherIDIDs(ids...)
}

// AddTeachersIDIDs adds the Teachers_ID edge to Lessonplan by ids.
func (tuo *TeacherUpdateOne) AddTeachersIDIDs(ids ...int) *TeacherUpdateOne {
	tuo.mutation.AddTeachersIDIDs(ids...)
	return tuo
}

// AddTeachersID adds the Teachers_ID edges to Lessonplan.
func (tuo *TeacherUpdateOne) AddTeachersID(l ...*Lessonplan) *TeacherUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tuo.AddTeachersIDIDs(ids...)
}

// Mutation returns the TeacherMutation object of the builder.
func (tuo *TeacherUpdateOne) Mutation() *TeacherMutation {
	return tuo.mutation
}

// RemoveTeacherIDIDs removes the Teacher_ID edge to Subject by ids.
func (tuo *TeacherUpdateOne) RemoveTeacherIDIDs(ids ...int) *TeacherUpdateOne {
	tuo.mutation.RemoveTeacherIDIDs(ids...)
	return tuo
}

// RemoveTeacherID removes Teacher_ID edges to Subject.
func (tuo *TeacherUpdateOne) RemoveTeacherID(s ...*Subject) *TeacherUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.RemoveTeacherIDIDs(ids...)
}

// RemoveTeachersIDIDs removes the Teachers_ID edge to Lessonplan by ids.
func (tuo *TeacherUpdateOne) RemoveTeachersIDIDs(ids ...int) *TeacherUpdateOne {
	tuo.mutation.RemoveTeachersIDIDs(ids...)
	return tuo
}

// RemoveTeachersID removes Teachers_ID edges to Lessonplan.
func (tuo *TeacherUpdateOne) RemoveTeachersID(l ...*Lessonplan) *TeacherUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tuo.RemoveTeachersIDIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (tuo *TeacherUpdateOne) Save(ctx context.Context) (*Teacher, error) {

	var (
		err  error
		node *Teacher
	)
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TeacherMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TeacherUpdateOne) SaveX(ctx context.Context) *Teacher {
	t, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return t
}

// Exec executes the query on the entity.
func (tuo *TeacherUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TeacherUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TeacherUpdateOne) sqlSave(ctx context.Context) (t *Teacher, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   teacher.Table,
			Columns: teacher.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: teacher.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Teacher.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := tuo.mutation.TeacherName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: teacher.FieldTeacherName,
		})
	}
	if nodes := tuo.mutation.RemovedTeacherIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeacherIDTable,
			Columns: []string{teacher.TeacherIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subject.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.TeacherIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeacherIDTable,
			Columns: []string{teacher.TeacherIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subject.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := tuo.mutation.RemovedTeachersIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeachersIDTable,
			Columns: []string{teacher.TeachersIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lessonplan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.TeachersIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   teacher.TeachersIDTable,
			Columns: []string{teacher.TeachersIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lessonplan.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	t = &Teacher{config: tuo.config}
	_spec.Assign = t.assignValues
	_spec.ScanValues = t.scanValues()
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teacher.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return t, nil
}
