/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntLessonplan,
    EntLessonplanFromJSON,
    EntLessonplanFromJSONTyped,
    EntLessonplanToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSectionEdges
 */
export interface EntSectionEdges {
    /**
     * SecID holds the value of the sec_id edge.
     * @type {Array<EntLessonplan>}
     * @memberof EntSectionEdges
     */
    secID?: Array<EntLessonplan>;
}

export function EntSectionEdgesFromJSON(json: any): EntSectionEdges {
    return EntSectionEdgesFromJSONTyped(json, false);
}

export function EntSectionEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSectionEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'secID': !exists(json, 'secID') ? undefined : ((json['secID'] as Array<any>).map(EntLessonplanFromJSON)),
    };
}

export function EntSectionEdgesToJSON(value?: EntSectionEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'secID': value.secID === undefined ? undefined : ((value.secID as Array<any>).map(EntLessonplanToJSON)),
    };
}


