/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntTeacherEdges,
    EntTeacherEdgesFromJSON,
    EntTeacherEdgesFromJSONTyped,
    EntTeacherEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTeacher
 */
export interface EntTeacher {
    /**
     * TeacherName holds the value of the "Teacher_Name" field.
     * @type {string}
     * @memberof EntTeacher
     */
    teacherName?: string;
    /**
     * 
     * @type {EntTeacherEdges}
     * @memberof EntTeacher
     */
    edges?: EntTeacherEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntTeacher
     */
    id?: number;
}

export function EntTeacherFromJSON(json: any): EntTeacher {
    return EntTeacherFromJSONTyped(json, false);
}

export function EntTeacherFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTeacher {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teacherName': !exists(json, 'Teacher_Name') ? undefined : json['Teacher_Name'],
        'edges': !exists(json, 'edges') ? undefined : EntTeacherEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntTeacherToJSON(value?: EntTeacher | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Teacher_Name': value.teacherName,
        'edges': EntTeacherEdgesToJSON(value.edges),
        'id': value.id,
    };
}


