// Code generated by entc, DO NOT EDIT.

package teacher

const (
	// Label holds the string label denoting the teacher type in the database.
	Label = "teacher"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTeacherName holds the string denoting the teacher_name field in the database.
	FieldTeacherName = "teacher_name"

	// EdgeTeacherID holds the string denoting the teacher_id edge name in mutations.
	EdgeTeacherID = "Teacher_ID"
	// EdgeTeachersID holds the string denoting the teachers_id edge name in mutations.
	EdgeTeachersID = "Teachers_ID"

	// Table holds the table name of the teacher in the database.
	Table = "teachers"
	// TeacherIDTable is the table the holds the Teacher_ID relation/edge.
	TeacherIDTable = "subjects"
	// TeacherIDInverseTable is the table name for the Subject entity.
	// It exists in this package in order to avoid circular dependency with the "subject" package.
	TeacherIDInverseTable = "subjects"
	// TeacherIDColumn is the table column denoting the Teacher_ID relation/edge.
	TeacherIDColumn = "teacher_teacher_id"
	// TeachersIDTable is the table the holds the Teachers_ID relation/edge.
	TeachersIDTable = "lessonplans"
	// TeachersIDInverseTable is the table name for the Lessonplan entity.
	// It exists in this package in order to avoid circular dependency with the "lessonplan" package.
	TeachersIDInverseTable = "lessonplans"
	// TeachersIDColumn is the table column denoting the Teachers_ID relation/edge.
	TeachersIDColumn = "teacher_teachers_id"
)

// Columns holds all SQL columns for teacher fields.
var Columns = []string{
	FieldID,
	FieldTeacherName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Teacher type.
var ForeignKeys = []string{
	"user_user_id",
}
