// Code generated by entc, DO NOT EDIT.

package section

const (
	// Label holds the string label denoting the section type in the database.
	Label = "section"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroup holds the string denoting the group field in the database.
	FieldGroup = "group"
	// FieldRecieve holds the string denoting the recieve field in the database.
	FieldRecieve = "recieve"
	// FieldSeatLeft holds the string denoting the seat_left field in the database.
	FieldSeatLeft = "seat_left"
	// FieldRoom holds the string denoting the room field in the database.
	FieldRoom = "room"
	// FieldDateTime holds the string denoting the date_time field in the database.
	FieldDateTime = "date_time"

	// EdgeSecID holds the string denoting the sec_id edge name in mutations.
	EdgeSecID = "sec_id"

	// Table holds the table name of the section in the database.
	Table = "sections"
	// SecIDTable is the table the holds the sec_id relation/edge.
	SecIDTable = "lessonplans"
	// SecIDInverseTable is the table name for the Lessonplan entity.
	// It exists in this package in order to avoid circular dependency with the "lessonplan" package.
	SecIDInverseTable = "lessonplans"
	// SecIDColumn is the table column denoting the sec_id relation/edge.
	SecIDColumn = "section_sec_id"
)

// Columns holds all SQL columns for section fields.
var Columns = []string{
	FieldID,
	FieldGroup,
	FieldRecieve,
	FieldSeatLeft,
	FieldRoom,
	FieldDateTime,
}

var (
	// GroupValidator is a validator for the "Group" field. It is called by the builders before save.
	GroupValidator func(int) error
	// RecieveValidator is a validator for the "recieve" field. It is called by the builders before save.
	RecieveValidator func(int) error
	// SeatLeftValidator is a validator for the "Seat_left" field. It is called by the builders before save.
	SeatLeftValidator func(int) error
	// RoomValidator is a validator for the "Room" field. It is called by the builders before save.
	RoomValidator func(string) error
	// DateTimeValidator is a validator for the "Date_Time" field. It is called by the builders before save.
	DateTimeValidator func(string) error
)
