// Code generated by entc, DO NOT EDIT.

package section

import (
	"github.com/USER/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Group applies equality check predicate on the "Group" field. It's identical to GroupEQ.
func Group(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroup), v))
	})
}

// Recieve applies equality check predicate on the "recieve" field. It's identical to RecieveEQ.
func Recieve(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRecieve), v))
	})
}

// SeatLeft applies equality check predicate on the "Seat_left" field. It's identical to SeatLeftEQ.
func SeatLeft(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatLeft), v))
	})
}

// Room applies equality check predicate on the "Room" field. It's identical to RoomEQ.
func Room(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoom), v))
	})
}

// DateTime applies equality check predicate on the "Date_Time" field. It's identical to DateTimeEQ.
func DateTime(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDateTime), v))
	})
}

// GroupEQ applies the EQ predicate on the "Group" field.
func GroupEQ(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroup), v))
	})
}

// GroupNEQ applies the NEQ predicate on the "Group" field.
func GroupNEQ(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGroup), v))
	})
}

// GroupIn applies the In predicate on the "Group" field.
func GroupIn(vs ...int) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldGroup), v...))
	})
}

// GroupNotIn applies the NotIn predicate on the "Group" field.
func GroupNotIn(vs ...int) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldGroup), v...))
	})
}

// GroupGT applies the GT predicate on the "Group" field.
func GroupGT(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGroup), v))
	})
}

// GroupGTE applies the GTE predicate on the "Group" field.
func GroupGTE(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGroup), v))
	})
}

// GroupLT applies the LT predicate on the "Group" field.
func GroupLT(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGroup), v))
	})
}

// GroupLTE applies the LTE predicate on the "Group" field.
func GroupLTE(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGroup), v))
	})
}

// RecieveEQ applies the EQ predicate on the "recieve" field.
func RecieveEQ(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRecieve), v))
	})
}

// RecieveNEQ applies the NEQ predicate on the "recieve" field.
func RecieveNEQ(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRecieve), v))
	})
}

// RecieveIn applies the In predicate on the "recieve" field.
func RecieveIn(vs ...int) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRecieve), v...))
	})
}

// RecieveNotIn applies the NotIn predicate on the "recieve" field.
func RecieveNotIn(vs ...int) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRecieve), v...))
	})
}

// RecieveGT applies the GT predicate on the "recieve" field.
func RecieveGT(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRecieve), v))
	})
}

// RecieveGTE applies the GTE predicate on the "recieve" field.
func RecieveGTE(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRecieve), v))
	})
}

// RecieveLT applies the LT predicate on the "recieve" field.
func RecieveLT(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRecieve), v))
	})
}

// RecieveLTE applies the LTE predicate on the "recieve" field.
func RecieveLTE(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRecieve), v))
	})
}

// SeatLeftEQ applies the EQ predicate on the "Seat_left" field.
func SeatLeftEQ(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatLeft), v))
	})
}

// SeatLeftNEQ applies the NEQ predicate on the "Seat_left" field.
func SeatLeftNEQ(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSeatLeft), v))
	})
}

// SeatLeftIn applies the In predicate on the "Seat_left" field.
func SeatLeftIn(vs ...int) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSeatLeft), v...))
	})
}

// SeatLeftNotIn applies the NotIn predicate on the "Seat_left" field.
func SeatLeftNotIn(vs ...int) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSeatLeft), v...))
	})
}

// SeatLeftGT applies the GT predicate on the "Seat_left" field.
func SeatLeftGT(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSeatLeft), v))
	})
}

// SeatLeftGTE applies the GTE predicate on the "Seat_left" field.
func SeatLeftGTE(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSeatLeft), v))
	})
}

// SeatLeftLT applies the LT predicate on the "Seat_left" field.
func SeatLeftLT(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSeatLeft), v))
	})
}

// SeatLeftLTE applies the LTE predicate on the "Seat_left" field.
func SeatLeftLTE(v int) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSeatLeft), v))
	})
}

// RoomEQ applies the EQ predicate on the "Room" field.
func RoomEQ(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRoom), v))
	})
}

// RoomNEQ applies the NEQ predicate on the "Room" field.
func RoomNEQ(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRoom), v))
	})
}

// RoomIn applies the In predicate on the "Room" field.
func RoomIn(vs ...string) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRoom), v...))
	})
}

// RoomNotIn applies the NotIn predicate on the "Room" field.
func RoomNotIn(vs ...string) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRoom), v...))
	})
}

// RoomGT applies the GT predicate on the "Room" field.
func RoomGT(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRoom), v))
	})
}

// RoomGTE applies the GTE predicate on the "Room" field.
func RoomGTE(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRoom), v))
	})
}

// RoomLT applies the LT predicate on the "Room" field.
func RoomLT(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRoom), v))
	})
}

// RoomLTE applies the LTE predicate on the "Room" field.
func RoomLTE(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRoom), v))
	})
}

// RoomContains applies the Contains predicate on the "Room" field.
func RoomContains(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRoom), v))
	})
}

// RoomHasPrefix applies the HasPrefix predicate on the "Room" field.
func RoomHasPrefix(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRoom), v))
	})
}

// RoomHasSuffix applies the HasSuffix predicate on the "Room" field.
func RoomHasSuffix(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRoom), v))
	})
}

// RoomEqualFold applies the EqualFold predicate on the "Room" field.
func RoomEqualFold(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRoom), v))
	})
}

// RoomContainsFold applies the ContainsFold predicate on the "Room" field.
func RoomContainsFold(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRoom), v))
	})
}

// DateTimeEQ applies the EQ predicate on the "Date_Time" field.
func DateTimeEQ(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDateTime), v))
	})
}

// DateTimeNEQ applies the NEQ predicate on the "Date_Time" field.
func DateTimeNEQ(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDateTime), v))
	})
}

// DateTimeIn applies the In predicate on the "Date_Time" field.
func DateTimeIn(vs ...string) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDateTime), v...))
	})
}

// DateTimeNotIn applies the NotIn predicate on the "Date_Time" field.
func DateTimeNotIn(vs ...string) predicate.Section {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Section(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDateTime), v...))
	})
}

// DateTimeGT applies the GT predicate on the "Date_Time" field.
func DateTimeGT(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDateTime), v))
	})
}

// DateTimeGTE applies the GTE predicate on the "Date_Time" field.
func DateTimeGTE(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDateTime), v))
	})
}

// DateTimeLT applies the LT predicate on the "Date_Time" field.
func DateTimeLT(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDateTime), v))
	})
}

// DateTimeLTE applies the LTE predicate on the "Date_Time" field.
func DateTimeLTE(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDateTime), v))
	})
}

// DateTimeContains applies the Contains predicate on the "Date_Time" field.
func DateTimeContains(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDateTime), v))
	})
}

// DateTimeHasPrefix applies the HasPrefix predicate on the "Date_Time" field.
func DateTimeHasPrefix(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDateTime), v))
	})
}

// DateTimeHasSuffix applies the HasSuffix predicate on the "Date_Time" field.
func DateTimeHasSuffix(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDateTime), v))
	})
}

// DateTimeEqualFold applies the EqualFold predicate on the "Date_Time" field.
func DateTimeEqualFold(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDateTime), v))
	})
}

// DateTimeContainsFold applies the ContainsFold predicate on the "Date_Time" field.
func DateTimeContainsFold(v string) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDateTime), v))
	})
}

// HasSecID applies the HasEdge predicate on the "sec_id" edge.
func HasSecID() predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SecIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SecIDTable, SecIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSecIDWith applies the HasEdge predicate on the "sec_id" edge with a given conditions (other predicates).
func HasSecIDWith(preds ...predicate.Lessonplan) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SecIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SecIDTable, SecIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Section) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Section) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Section) predicate.Section {
	return predicate.Section(func(s *sql.Selector) {
		p(s.Not())
	})
}
